# tabspaces = 4

import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetbrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true  # Automatically save selections to clipboard
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"  # Characters considered as semantic boundaries

[window]
opacity = 0.95  # Window transparency
startup_mode = "Windowed"  # Start in windowed mode
option_as_alt = "Both"  # Treat Option key as Alt for both left and right Option keys

[keyboard]
bindings = [
  # Font size controls
  { action = "ResetFontSize", key = "Key0", mods = "Command" },
  { action = "IncreaseFontSize", key = "Equals", mods = "Command" },
  { action = "DecreaseFontSize", key = "Minus", mods = "Command" },

  # Tmux-like control sequences
  { chars = "\u0002c", key = "T", mods = "Command" },
  { chars = "\u0002\"", key = "D", mods = "Command" },
  { chars = "\u0002%", key = "Return", mods = "Command" },
  { chars = "\u0002[?", key = "F", mods = "Command" },
  { chars = "\u0002z", key = "Z", mods = "Command" },
  { chars = "\u0002 ", key = "Z", mods = "Command|Shift" },

  # Navigation bindings
  { chars = "\u0002h", key = "Left", mods = "Alt" },
  { chars = "\u0002j", key = "Down", mods = "Alt" },
  { chars = "\u0002k", key = "Up", mods = "Alt" },
  { chars = "\u0002l", key = "Right", mods = "Alt" },

  # Shift-modified navigation bindings
  { chars = "\u0002H", key = "H", mods = "Alt|Shift" },
  { chars = "\u0002J", key = "J", mods = "Alt|Shift" },
  { chars = "\u0002K", key = "K", mods = "Alt|Shift" },
  { chars = "\u0002L", key = "L", mods = "Alt|Shift" },

  # Pane management bindings
  { chars = "\u0002p", key = "LBracket", mods = "Command" },
  { chars = "\u0002n", key = "RBracket", mods = "Command" },

  # Window & Session switch
  { chars = "\u0002w", key = "U", mods = "Command" },
  { chars = "\u0002s", key = "I", mods = "Command" },

  # Miscellaneous controls
  { chars = "\f", key = "K", mods = "Command", mode = "~Vi|~Search" },
  { action = "ClearHistory", key = "K", mods = "Command", mode = "~Vi|~Search" },
  { action = "Paste", key = "V", mods = "Command" },
  { action = "Copy", key = "C", mods = "Command" },

  # { action = "ClearSelection", key = "C", mods = "Command", mode = "Vi|~Search" },
  # { action = "SpawnNewInstance", key = "N", mods = "Command" },
]

